menu:
- {name: 'home', url: '/'}
# - {name: 'interests', url: '/interests'}
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/pmcal'}
- {icon: 'twitter', link: 'https://twitter.com/_pedrocal'}
- {icon: 'instagram', link: 'https://www.instagram.com/_pedro_cal/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/pedro-cal-a36a22233/'}

contacts:
- {name: 'Pedro Cal', title: 'Software Engineer', email: 'me[at]pedrocal[dot]com', image: 'assets/img/contact.jpg'}
